version: "3.8"

services:
  api_service:
    build: ./ApiService
    stdin_open: true
    tty: true
    depends_on:
      - buyer_service
      - inventory_service
      - merchant_service
      - payment_service
    ports:
      - 8000:8000
    volumes:
      - ./ApiService:/app/data
    
  order_service:
    build: ./OrderService
    stdin_open: true
    tty: true
    expose:
      - 8000
    depends_on:
      - order_db
      - rabbitmq-host
    environment:
      - postgres_host=order_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=orders
    volumes:
      - ./OrderService:/app/data
      
  merchant_service:
    build: ./MerchantService
    stdin_open: true
    tty: true
    expose:
      - 8001
    depends_on:
      - merchants_db
      - rabbitmq-host
    environment:
      - postgres_host=merchants_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=merchants
    volumes:
      - ./MerchantService:/app/data

  buyer_service:
    build: ./BuyerService
    stdin_open: true
    tty: true
    expose:
      - 8002
    depends_on:
      - buyer_db
      - rabbitmq-host
    environment:
      - postgres_host=buyer_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=buyers
    volumes:
      - ./BuyerService:/app/data
  
  inventory_service:
    build: ./InventoryService
    stdin_open: true
    tty: true
    expose:
      - 8003
    depends_on:
      - inventory_db
      - rabbitmq-host
    environment:
      - postgres_host=inventory_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=products
    volumes:
      - ./InventoryService:/app/data

  payment_service:
    build: ./PaymentService
    tty: true
    depends_on:
      - rabbitmq-host
      - order_service
    volumes:
      - payment_service_vol:/app/data

  email_service:
    build: ./EmailService
    tty: true
    depends_on:
      - payment_service
      - rabbitmq-host
      - order_service

  order_db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    expose:
      - 5433
    volumes:
      - ./OrderService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/orderdata

  merchants_db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=merchants
    expose:
      - 5430
    volumes:
      - ./MerchantService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/merchantdata

  buyer_db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=buyers
    expose:
      - 5431
    volumes:
      - ./BuyerService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/buyerdata

  inventory_db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    expose:
      - 5432
    volumes:
      - ./InventoryService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/inventorydata

  rabbitmq-host:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  data:
  payment_service_vol:
  postgres-data: 
