version: "3.8"

services:
  order_service:
    build: ./OrderService
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - order_db
    environment:
      - postgres_host=order_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=orders
      
  merchant_service:
    build: ./MerchantService
    stdin_open: true
    tty: true
    ports:
      - 8001:8001
    depends_on:
      - rabbitmq
      - merchants_db
    environment:
      - postgres_host=merchants_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=merchants

  inventory_service:
    build: ./InventoryService
    stdin_open: true
    tty: true
    ports: 
      - 8003:8003
    depends_on:
      - rabbitmq
      - inventory_db
    environment:
      - postgres_host=inventory_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=products
      
  buyer_service:
    build: ./BuyerService
    stdin_open: true
    tty: true
    ports:  
      - "8002:8002"
    depends_on:
      - buyer_db
      - rabbitmq
    environment:
      - postgres_host=buyer_db
      - postgres_user=postgres
      - postgres_password=postgres
      - postgres_database=buyers
  
  order_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    ports:
      - 5435:5432
    volumes:
      - ./OrderService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/orderdata

  merchants_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=merchants
    ports:
      - 5432:5432
    volumes:
      - ./MerchantService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/merchantdata

  buyer_db:
    image: postgres:14
    hostname: buyer_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=buyers
    ports:
      - 5433:5432
    volumes:
      - ./BuyerService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  inventory_db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    ports:
      - 5434:5432
    volumes:
      - ./InventoryService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/inventorydata

  payment_service:
    build: ./PaymentService
    # restart: always
    tty: true
    depends_on:
      - rabbitmq
      # - order_service
    volumes:
      - payment_service_vol:/app/data

  email_service:
    build: ./EmailService
    # restart: always
    tty: true
    depends_on:
      - rabbitmq
      - payment_service
      # - order_service

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq-host'
    ports:
      - 5672:5672
      - 15672:15672
      
volumes:
  data:
  payment_service_vol:
  postgres-data: 
