version: '3.8'
services:
  buyer_service:
    build: ./BuyerService
    stdin_open: true
    tty: true
    depends_on:
      - buyer_db
    ports:  
      - "8000:8000"
  buyer_db:
    image: postgres
    hostname: buyer_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: buyer_db
    ports:
      - "5432:5432"
    volumes:
      - ./BuyerService/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
volumes:
  data: 
